// Copyright (C) 2017 Juan José Casafranca.
// SPDX-License-Identifier: LicenseRef-Qt-Commercial OR BSD-3-Clause

#version 430 core

layout (local_size_x=32) in;

layout (std430, binding = 1) buffer input
{
    uint d[];
};

layout (location=1) uniform int inputSize;

void main()
{
    if (gl_GlobalInvocationID.x < inputSize)
        d[gl_GlobalInvocationID.x] = d[gl_GlobalInvocationID.x] + gl_GlobalInvocationID.x * 2;
}
