include(global/global.pri)
include(painting/painting.pri)
include(arrays/arrays.pri)
include(effects/effects.pri)
include(materials/materials.pri)
include(geometry/geometry.pri)
include(viewing/viewing.pri)
include(math3d/math3d.pri)
include(scene/scene.pri)
include(network/network.pri)
include(graphicsview/graphicsview.pri)
include(textures/textures.pri)
include(surfaces/surfaces.pri)
include(api/api.pri)

